"""
followup_planner.py — Feature 4: Follow-up & Monitoring Planner.

Generates a structured follow-up plan (next review date, recommended tests,
imaging, monitoring interval, warning symptoms, doctor visit schedule) after
Clinical Strategy Synthesis / General Wellness Synthesis. The review interval
is derived deterministically from urgency tier (so it's consistent and
auditable); the clinically-specific test/imaging/warning-symptom content is
generated by the LLM against the same PrescriptionPlan/RiskAssessment schema
pattern used elsewhere in workflow.py.
"""
from __future__ import annotations

import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

# Deterministic review cadence by urgency tier (days).
_REVIEW_INTERVAL_DAYS = {
    "CRITICAL": 3,
    "HIGH": 14,
    "MODERATE": 30,
    "LOW": 90,
}


class FollowUpPlan(BaseModel):
    next_review_date: str = Field(..., description="Calendar date of the next recommended review")
    review_interval_days: int = Field(..., description="Days until next review")
    recommended_tests: List[str] = Field(default_factory=list, description="Blood work / lab tests")
    imaging_studies: List[str] = Field(default_factory=list, description="Imaging studies, if needed")
    monitoring_interval: str = Field(..., description="How often vitals/markers should be monitored at home")
    warning_symptoms: List[str] = Field(default_factory=list, description="Symptoms that should trigger urgent care")
    doctor_visit_schedule: str = Field(..., description="Recommended cadence/type of in-person visits")


class FollowUpPlanLLMResponse(BaseModel):
    """Schema used for the structured-output LLM call — date/interval are
    computed deterministically outside the LLM, so they're excluded here."""
    recommended_tests: List[str] = Field(..., description="Blood work / lab tests")
    imaging_studies: List[str] = Field(default_factory=list, description="Imaging studies, if needed; empty list if none")
    monitoring_interval: str = Field(..., description="Home monitoring cadence")
    warning_symptoms: List[str] = Field(..., description="Symptoms requiring urgent care")
    doctor_visit_schedule: str = Field(..., description="Recommended in-person visit cadence/type")


def compute_review_interval(urgency: str) -> int:
    return _REVIEW_INTERVAL_DAYS.get(urgency, 30)


def generate_followup_plan(
    llm,
    urgency: str,
    disease_risks_text: str,
    medications_text: str,
    risk_flags: List[str],
) -> FollowUpPlan:
    from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, SystemMessagePromptTemplate

    interval_days = compute_review_interval(urgency)
    next_review = datetime.date.today() + datetime.timedelta(days=interval_days)

    followup_prompt = ChatPromptTemplate.from_messages([
        SystemMessagePromptTemplate.from_template(
            """
            You are a clinical monitoring planner. Generate a structured, evidence-based
            follow-up and monitoring plan.

            Rules:
            - Recommend specific, relevant lab tests (e.g. CBC, HbA1c, Lipid Profile,
              Blood Pressure, Kidney Function) based on the disease risks and medications.
            - If the input below includes a "Clinical Considerations" block (conditions raised
              by clinical reasoning with no ML score), you MUST include at least one specific,
              standard test or imaging study that would help confirm or rule out EACH one —
              e.g. suspected Myocardial Infarction -> Troponin + ECG; suspected Pulmonary
              Embolism or DVT -> D-dimer (+ CT pulmonary angiogram/Doppler ultrasound if
              indicated); suspected Hypothyroidism -> TSH/Free T4; suspected Kidney Disease ->
              eGFR/Creatinine/Urinalysis; suspected infection (e.g. COVID-19) -> the relevant
              diagnostic test. Do not silently drop a listed consideration from the test list.
            - Only recommend imaging if clinically justified by the risk profile; otherwise
              return an empty list.
            - Warning symptoms must be specific and actionable (e.g. "chest pain",
              "shortness of breath"), not vague.
            - Do NOT diagnose or prescribe medications.
            - Do NOT assign or imply a probability/percentage to anything listed as a
              Clinical Consideration — reference it qualitatively only when explaining why a
              test is recommended.
            - Output strictly in JSON matching the provided schema.
            """
        ),
        HumanMessagePromptTemplate.from_template(
            """
            Urgency Tier: {urgency}
            Risk Flags: {risk_flags}

            Disease Risks:
            {risks}

            Current Medications:
            {medications}

            Generate the follow-up and monitoring plan.
            """
        )
    ])

    chain = followup_prompt | llm.with_structured_output(FollowUpPlanLLMResponse)
    result = chain.invoke({
        "urgency": urgency,
        "risk_flags": ", ".join(risk_flags) if risk_flags else "None",
        "risks": disease_risks_text or "None identified",
        "medications": medications_text or "None",
    })

    if not result.recommended_tests:
        result.recommended_tests = ["CBC", "Basic Metabolic Panel"]
    if not result.warning_symptoms:
        result.warning_symptoms = ["Chest pain", "Shortness of breath", "Severe dizziness"]

    return FollowUpPlan(
        next_review_date=next_review.isoformat(),
        review_interval_days=interval_days,
        recommended_tests=result.recommended_tests,
        imaging_studies=result.imaging_studies,
        monitoring_interval=result.monitoring_interval,
        warning_symptoms=result.warning_symptoms,
        doctor_visit_schedule=result.doctor_visit_schedule,
    )