"""
retrain_heart_model.py

WHY THIS SCRIPT EXISTS — READ THIS BEFORE RUNNING IT:
Direct testing of your shipped heart_model.pkl found something more specific
than "suspiciously perfect metrics." Age and Cholesterol alone account for
~90% of total gain, and an ablation test confirms Chest Pain Type, Diabetes
history, Obesity, and Exercise-Induced Angina — clinically some of the most
predictive features for heart disease — change the predicted probability by
EXACTLY ZERO at a fixed age/cholesterol:

    age=55, chol=220, Chest Pain Type=Typical Angina -> 0.98620737
    age=55, chol=220, Diabetes=Yes                   -> 0.98620737  (identical)
    age=55, chol=220, Obesity=Yes                     -> 0.98620737  (identical)
    age=55, chol=220, Exercise-Induced Angina=Yes      -> 0.98620737  (identical)

And the age/cholesterol decision surface is an extremely steep cliff, not a
gradual clinical risk gradient:

    age=50, chol=220 -> ~0.01        age=55, chol=220 -> ~0.99

UNLIKE the hypertension fix (BP_History was a genuinely droppable leaking
column), THIS problem is very unlikely to be fixable by tuning hyperparameters
or dropping one feature — the pattern (a near-step-function on 2 variables,
14 other real features carrying near-zero weight) is the signature of a
TRAINING DATASET whose target label was itself generated by a simple rule
(e.g. "if age > X and cholesterol > Y") rather than real clinical outcomes.
If that's the case here, retraining on the SAME CSV will very likely just
reproduce the same 2-variable model, no matter what hyperparameters you use.

WHAT THIS SCRIPT DOES:
1. Retrains with meaningfully stronger regularization (shallower trees,
   higher min_child_weight, feature subsampling) than a default grid search
   would pick, which is the correct move IF the signal is real but the
   original model was simply allowed to overfit onto the two strongest
   features.
2. Prints an "unused features" diagnostic after training so you can
   immediately see whether the SAME collapse happens again even under
   regularization — which would be strong confirmation the issue is the
   dataset, not the hyperparameters.

IF THE DIAGNOSTIC STILL SHOWS COLLAPSE AFTER THIS SCRIPT:
The real fix is sourcing a dataset with genuine clinical signal across these
features — for example the UCI Heart Disease dataset (Cleveland/Hungarian/
Switzerland/VA, available via the UCI ML Repository or as "heart.csv" /
"heart_disease_uci.csv" on Kaggle), which is real (if small) clinical data
where chest pain type, ST depression, and exercise-induced angina are
well-documented as genuinely predictive. This script's feature list is kept
compatible with that dataset's typical schema as far as possible so it's a
reasonable next step if you go that route.

USAGE:
    python retrain_heart_model.py --data path/to/your_heart_dataset.csv
"""
import argparse
import json
import os

import joblib
import pandas as pd
import shap
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

OUTPUT_DIR = os.environ.get("CLINICAL_ML_MODELS_DIR", "ml_models")

FEATURE_COLUMNS = [
    "Age", "Cholesterol", "Blood Pressure", "Heart Rate", "Exercise Hours", "Stress Level",
    "Blood Sugar", "Gender_Male", "Smoking_Former", "Smoking_Never", "Alcohol Intake_Moderate",
    "Family History_Yes", "Diabetes_Yes", "Obesity_Yes", "Exercise Induced Angina_Yes",
    "Chest Pain Type_Atypical Angina", "Chest Pain Type_Non-anginal Pain", "Chest Pain Type_Typical Angina",
]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", required=True, help="Path to your original heart disease training CSV")
    parser.add_argument("--target-col", default="Heart_Disease", help="ADAPT THIS if your target column differs")
    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--random-state", type=int, default=42)
    args = parser.parse_args()

    df = pd.read_csv(args.data)
    if args.target_col not in df.columns:
        raise SystemExit(f"Target column '{args.target_col}' not found. Pass --target-col explicitly.")

    y = df[args.target_col]
    missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
    if missing:
        raise SystemExit(f"Expected columns missing from --data: {missing}.")
    X = df[FEATURE_COLUMNS]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=args.random_state, stratify=y
    )

    # Meaningfully more conservative than a default grid search would likely
    # pick: shallower trees, higher min_child_weight, column subsampling —
    # aimed at preventing the model from collapsing onto just 2 features
    # IF there is real signal spread across the others to find.
    model = XGBClassifier(
        n_estimators=150, max_depth=3, min_child_weight=15, gamma=0.5,
        subsample=0.7, colsample_bytree=0.6, learning_rate=0.05,
        random_state=args.random_state, eval_metric="logloss", use_label_encoder=False,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    metrics = {
        "Accuracy": float(accuracy_score(y_test, y_pred)),
        "Precision": float(precision_score(y_test, y_pred)),
        "Recall": float(recall_score(y_test, y_pred)),
        "F1": float(f1_score(y_test, y_pred)),
        "ROC_AUC": float(roc_auc_score(y_test, y_proba)),
    }
    print("\nRetrained held-out metrics:")
    for k, v in metrics.items():
        print(f"  {k}: {v:.4f}")

    # THE KEY DIAGNOSTIC: does the same collapse happen again?
    importances = dict(zip(FEATURE_COLUMNS, model.feature_importances_))
    top2_share = sorted(importances.values(), reverse=True)
    top2_pct = (top2_share[0] + top2_share[1]) * 100 if len(top2_share) >= 2 else 0
    zero_importance = [f for f, imp in importances.items() if imp < 1e-6]

    print(f"\nDIAGNOSTIC — top-2 features account for {top2_pct:.1f}% of importance "
          f"(was ~90% in the original model)")
    print(f"DIAGNOSTIC — {len(zero_importance)} feature(s) with ~zero importance: {zero_importance}")
    if top2_pct > 80 or len(zero_importance) >= 6:
        print(
            "\n*** STILL COLLAPSED even with stronger regularization. This is strong evidence the "
            "issue is the TRAINING DATA itself (synthetic/rule-generated labels), not the "
            "hyperparameters. Retraining again on this same CSV is unlikely to help further — see "
            "the module docstring for the recommended next step (a real clinical dataset). ***"
        )
    else:
        print("\nLooks meaningfully better distributed across features than the original model.")

    explainer = shap.TreeExplainer(model)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    joblib.dump(model, os.path.join(OUTPUT_DIR, "heart_model.pkl"))
    joblib.dump(FEATURE_COLUMNS, os.path.join(OUTPUT_DIR, "heart_feature_columns.pkl"))
    joblib.dump(explainer, os.path.join(OUTPUT_DIR, "heart_shap_explainer.pkl"))
    with open(os.path.join(OUTPUT_DIR, "heart_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=4)

    print(f"\nSaved retrained artifacts to {OUTPUT_DIR}/heart_*.pkl")


if __name__ == "__main__":
    main()
