# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i11_UdV5OoW7H2xVuZXitVBvEyItZMFe
"""

# ==========================================================
# PHASE 1 : IMPORT LIBRARIES
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import joblib

pd.set_option("display.max_columns",None)

# ==========================================================
# LOAD DATASET
# ==========================================================

df = pd.read_csv("diabetes_data.csv")

print("Dataset Loaded Successfully")

print(df.shape)

df.head()

df.info()

df.isnull().sum()

print("Duplicate Rows :",df.duplicated().sum())

df = df.drop_duplicates()

print(df.shape)

df.describe().T

print(df["Diabetes"].value_counts())

plt.figure(figsize=(5,4))

sns.countplot(
    x="Diabetes",
    data=df
)

plt.show()

X = df.drop("Diabetes",axis=1)

y = df["Diabetes"]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

feature_columns = X_train.columns.tolist()

joblib.dump(

    feature_columns,

    "diabetes_feature_columns.pkl"

)

print(X_train.shape)

print(X_test.shape)

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

xgb_model = XGBClassifier(

    objective="binary:logistic",

    random_state=42,

    eval_metric="logloss",

    n_estimators=200,

    learning_rate=0.05,

    max_depth=4,

    subsample=0.9,

    colsample_bytree=0.8
)

xgb_model.fit(X_train, y_train)

print("Model Trained Successfully")

y_pred = xgb_model.predict(X_test)

y_prob = xgb_model.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

roc = roc_auc_score(y_test, y_prob)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")
print(f"ROC AUC   : {roc:.4f}")

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

importance = pd.DataFrame({

    "Feature":X_train.columns,

    "Importance":xgb_model.feature_importances_

})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(15)

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance.head(15),
    x="Importance",
    y="Feature"
)

plt.title("Top 15 Important Features")

plt.show()

from sklearn.model_selection import cross_val_score

scores = cross_val_score(

    xgb_model,

    X,

    y,

    cv=5,

    scoring="roc_auc"

)

print("Cross Validation Scores")

print(scores)

print()

print("Mean ROC AUC :", scores.mean())

import joblib

joblib.dump(
    xgb_model,
    "diabetes_model.pkl"
)

print("diabetes_model.pkl Saved")

import json

metrics = {

    "Accuracy":float(accuracy),

    "Precision":float(precision),

    "Recall":float(recall),

    "F1":float(f1),

    "ROC_AUC":float(roc),

    "CrossValidation":float(scores.mean())

}

with open(

    "diabetes_metrics.json",

    "w"

) as f:

    json.dump(

        metrics,

        f,

        indent=4
    )

print("Metrics Saved")

from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

param_grid = {

    "n_estimators": [100, 200, 300, 400],

    "max_depth": [3, 4, 5, 6, 7],

    "learning_rate": [0.01, 0.05, 0.1, 0.2],

    "subsample": [0.7, 0.8, 0.9, 1.0],

    "colsample_bytree": [0.7, 0.8, 0.9, 1.0],

    "min_child_weight": [1, 3, 5],

    "gamma": [0, 0.1, 0.2]
}

random_search = RandomizedSearchCV(

    estimator=xgb,

    param_distributions=param_grid,

    n_iter=20,

    scoring="roc_auc",

    cv=5,

    random_state=42,

    n_jobs=-1,

    verbose=1

)

random_search.fit(X_train, y_train)

print("Best Parameters")

print(random_search.best_params_)

best_model = random_search.best_estimator_

y_pred = best_model.predict(X_test)

y_prob = best_model.predict_proba(X_test)[:,1]

from sklearn.metrics import *

print("Accuracy :", accuracy_score(y_test, y_pred))

print("Precision :", precision_score(y_test, y_pred))

print("Recall :", recall_score(y_test, y_pred))

print("F1 :", f1_score(y_test, y_pred))

print("ROC AUC :", roc_auc_score(y_test, y_prob))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("XGBoost Confusion Matrix")

plt.show()

importance = pd.DataFrame({

    "Feature": X_train.columns,

    "Importance": best_model.feature_importances_

})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(15)

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance.head(15),
    x="Importance",
    y="Feature"
)

plt.title("Top 15 Important Features")

plt.show()

import joblib

joblib.dump(best_model, "diabetes_model.pkl")

print("Model Saved Successfully")

import json

with open("diabetes_best_params.json", "w") as f:
    json.dump(random_search.best_params_, f, indent=4)

metrics = {

    "Accuracy": accuracy_score(y_test, y_pred),

    "Precision": precision_score(y_test, y_pred),

    "Recall": recall_score(y_test, y_pred),

    "F1": f1_score(y_test, y_pred),

    "ROC_AUC": roc_auc_score(y_test, y_prob)

}

with open("diabetes_metrics.json", "w") as f:
    json.dump(metrics, f, indent=4)

!pip install shap

import shap
import joblib

explainer = shap.TreeExplainer(best_model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(
    shap_values,
    X_test
)

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar"
)

sample = 0

shap.plots.waterfall(
    shap.Explanation(
        values=shap_values[sample],
        base_values=explainer.expected_value,
        data=X_test.iloc[sample],
        feature_names=X_test.columns
    )
)

shap.initjs()

shap.force_plot(
    explainer.expected_value,
    shap_values[0],
    X_test.iloc[0]
)

joblib.dump(
    explainer,
    "diabetes_shap_explainer.pkl"
)

print("SHAP Explainer Saved")

sample = X_test.iloc[[0]]

prediction = best_model.predict(sample)[0]

probability = best_model.predict_proba(sample)[0][1]

print("Prediction :", prediction)

print("Probability :", round(probability * 100, 2), "%")

from google.colab import files

files.download("diabetes_model.pkl")
files.download("diabetes_feature_columns.pkl")
files.download("diabetes_metrics.json")
files.download("diabetes_best_params.json")
files.download("diabetes_shap_explainer.pkl")

