# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i11_UdV5OoW7H2xVuZXitVBvEyItZMFe
"""

# =====================================================
# PHASE 1 : IMPORT LIBRARIES
# =====================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# =====================================================
# LOAD DATASET
# =====================================================

df = pd.read_csv("heart_disease_dataset.csv")

print("Dataset Loaded Successfully!")

# =====================================================
# DATASET SHAPE
# =====================================================

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.head()

df.info()

print(df.columns.tolist())

df.describe().T

missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing[missing["Missing Values"]>0]

missing

df.dtypes

for col in df.columns:
    print("="*60)
    print(col)
    print(df[col].unique())

print(df["Heart Disease"].value_counts())

plt.figure(figsize=(6,4))

sns.countplot(
    data=df,
    x="Heart Disease",
    palette="Set2"
)

plt.title("Heart Disease Distribution")

plt.show()

print("Minimum Age :", df["Age"].min())
print("Maximum Age :", df["Age"].max())

print("Minimum BP :", df["Blood Pressure"].min())
print("Maximum BP :", df["Blood Pressure"].max())

print("Minimum Cholesterol :", df["Cholesterol"].min())
print("Maximum Cholesterol :", df["Cholesterol"].max())

print("Minimum Blood Sugar :", df["Blood Sugar"].min())
print("Maximum Blood Sugar :", df["Blood Sugar"].max())

X = df.drop("Heart Disease", axis=1)
y = df["Heart Disease"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns

for col in numerical_cols:
    X[col] = X[col].fillna(X[col].median())

categorical_cols = X.select_dtypes(include="object").columns

for col in categorical_cols:
    X[col] = X[col].fillna(X[col].mode()[0])

X = pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True
)

print("Shape after Encoding :", X.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data :", X_train.shape)
print("Testing Data :", X_test.shape)

import joblib

feature_columns = X_train.columns.tolist()

joblib.dump(
    feature_columns,
    "heart_feature_columns.pkl"
)

print("Feature Columns Saved")

print("Missing Values in Training :", X_train.isnull().sum().sum())
print("Missing Values in Testing :", X_test.isnull().sum().sum())

# =====================================================
# IMPORT LIBRARIES
# =====================================================

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

xgb_model = XGBClassifier(

    objective="binary:logistic",

    random_state=42,

    eval_metric="logloss",

    n_estimators=200,

    learning_rate=0.05,

    max_depth=4,

    subsample=0.9,

    colsample_bytree=0.8
)

xgb_model.fit(X_train, y_train)

print("Model Trained Successfully!")

y_pred = xgb_model.predict(X_test)

y_prob = xgb_model.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

roc = roc_auc_score(y_test, y_prob)

print(f"Accuracy  : {accuracy:.4f}")

print(f"Precision : {precision:.4f}")

print(f"Recall    : {recall:.4f}")

print(f"F1 Score  : {f1:.4f}")

print(f"ROC AUC   : {roc:.4f}")

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt="d",

    cmap="Blues"

)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

importance = pd.DataFrame({

    "Feature":X_train.columns,

    "Importance":xgb_model.feature_importances_

})

importance = importance.sort_values(

    by="Importance",

    ascending=False
)

importance.head(15)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(

    xgb_model,

    X,

    y,

    cv=5,

    scoring="roc_auc"

)

print("Cross Validation Scores")

print(scores)

print()

print("Mean ROC AUC :", scores.mean())

import joblib

joblib.dump(

    xgb_model,

    "heart_model.pkl"
)

print("heart_model.pkl Saved")

import json

metrics = {

    "Accuracy":float(accuracy),

    "Precision":float(precision),

    "Recall":float(recall),

    "F1":float(f1),

    "ROC_AUC":float(roc),

    "CrossValidation":float(scores.mean())

}

with open(

    "heart_metrics.json",

    "w"

) as f:

    json.dump(

        metrics,

        f,

        indent=4
    )

print("Metrics Saved")

from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

xgb = XGBClassifier(
    objective="binary:logistic",
    random_state=42,
    eval_metric="logloss"
)

param_grid = {

    "n_estimators":[100,200,300,400],

    "max_depth":[3,4,5,6,7],

    "learning_rate":[0.01,0.05,0.1,0.2],

    "subsample":[0.7,0.8,0.9,1.0],

    "colsample_bytree":[0.7,0.8,0.9,1.0],

    "min_child_weight":[1,3,5],

    "gamma":[0,0.1,0.2,0.3]
}

random_search = RandomizedSearchCV(

    estimator=xgb,

    param_distributions=param_grid,

    n_iter=30,

    scoring="roc_auc",

    cv=5,

    verbose=1,

    random_state=42,

    n_jobs=-1
)

random_search.fit(X_train,y_train)

print("Best Parameters")

print(random_search.best_params_)

best_model = random_search.best_estimator_

y_pred = best_model.predict(X_test)

y_prob = best_model.predict_proba(X_test)[:,1]

from sklearn.metrics import *

print("Accuracy :",accuracy_score(y_test,y_pred))

print("Precision :",precision_score(y_test,y_pred))

print("Recall :",recall_score(y_test,y_pred))

print("F1 :",f1_score(y_test,y_pred))

print("ROC AUC :",roc_auc_score(y_test,y_prob))

import joblib

joblib.dump(

    best_model,

    "heart_model.pkl"
)

print("Model Saved Successfully")

import json

metrics = {

    "Accuracy":accuracy_score(y_test,y_pred),

    "Precision":precision_score(y_test,y_pred),

    "Recall":recall_score(y_test,y_pred),

    "F1":f1_score(y_test,y_pred),

    "ROC_AUC":roc_auc_score(y_test,y_prob)

}

with open(

    "heart_metrics.json",

    "w"

) as f:

    json.dump(

        metrics,

        f,

        indent=4
    )

import json

with open("heart_best_params.json", "w") as f:
    json.dump(random_search.best_params_, f, indent=4)

pip install shap

import shap
import joblib
import matplotlib.pyplot as plt

explainer = shap.TreeExplainer(best_model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(
    shap_values,
    X_test
)

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar"
)

sample = 0

shap.plots.waterfall(

    shap.Explanation(

        values=shap_values[sample],

        base_values=explainer.expected_value,

        data=X_test.iloc[sample],

        feature_names=X_test.columns

    )

)

shap.initjs()

shap.force_plot(

    explainer.expected_value,

    shap_values[0],

    X_test.iloc[0]

)

joblib.dump(

    explainer,

    "heart_shap_explainer.pkl"

)

print("SHAP Explainer Saved")

patient = X_test.iloc[[0]]

prediction = best_model.predict(patient)[0]

probability = best_model.predict_proba(patient)[0][1]

print("Prediction :", prediction)

print("Probability :", probability)

print("Files Generated")

print("""
heart_model.pkl

heart_feature_columns.pkl

heart_metrics.json

heart_best_params.json

heart_shap_explainer.pkl
""")

from google.colab import files

files.download("heart_model.pkl")
files.download("heart_feature_columns.pkl")
files.download("heart_metrics.json")
files.download("heart_best_params.json")
files.download("heart_shap_explainer.pkl")

