# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OA-PVjg-IMIWddBWMEBQtovTUrZ_WlL
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import joblib

pd.set_option("display.max_columns",None)

df = pd.read_csv("hypertension_dataset.csv")

print(df.shape)

df.head()

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

print(df.shape)

print(df["Has_Hypertension"].value_counts())

sns.countplot(
    x="Has_Hypertension",
    data=df
)

plt.show()

df = df.drop("Medication", axis=1)

df.head()

X = df.drop("Has_Hypertension",axis=1)

y = df["Has_Hypertension"]

from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

joblib.dump(
    target_encoder,
    "hypertension_target_encoder.pkl"
)

X = pd.get_dummies(

    X,

    drop_first=True
)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y
)

feature_columns = X_train.columns.tolist()

joblib.dump(

    feature_columns,

    "hypertension_feature_columns.pkl"
)

from xgboost import XGBClassifier

model = XGBClassifier(

    objective="binary:logistic",

    eval_metric="logloss",

    random_state=42
)

from sklearn.model_selection import RandomizedSearchCV

param_grid={

    "n_estimators":[100,200,300],

    "max_depth":[3,4,5,6],

    "learning_rate":[0.01,0.05,0.1],

    "subsample":[0.8,0.9,1],

    "colsample_bytree":[0.8,0.9,1]

}

search = RandomizedSearchCV(

    model,

    param_grid,

    cv=5,

    n_iter=20,

    scoring="roc_auc",

    random_state=42,

    n_jobs=-1
)

search.fit(X_train,y_train)

best_model = search.best_estimator_

y_pred = best_model.predict(X_test)

y_prob = best_model.predict_proba(X_test)[:,1]

from sklearn.metrics import *

print("Accuracy :",accuracy_score(y_test,y_pred))

print("Precision :",precision_score(y_test,y_pred))

print("Recall :",recall_score(y_test,y_pred))

print("F1 :",f1_score(y_test,y_pred))

print("ROC AUC :",roc_auc_score(y_test,y_prob))

cm = confusion_matrix(y_test,y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt="d",

    cmap="Blues"

)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

importance = pd.DataFrame({

    "Feature":X_train.columns,

    "Importance":best_model.feature_importances_

})

importance = importance.sort_values(

    by="Importance",

    ascending=False
)

importance.head(15)

plt.figure(figsize=(10,6))

sns.barplot(

    data=importance.head(15),

    x="Importance",

    y="Feature"

)

plt.show()

!pip install shap

import shap

explainer = shap.TreeExplainer(best_model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(

    shap_values,

    X_test
)

shap.summary_plot(

    shap_values,

    X_test,

    plot_type="bar"
)

joblib.dump(

    explainer,

    "hypertension_shap_explainer.pkl"
)

joblib.dump(

    best_model,

    "hypertension_model.pkl"
)

import json

with open(

    "hypertension_best_params.json",

    "w"

) as f:

    json.dump(

        search.best_params_,

        f,

        indent=4
    )

metrics={

    "Accuracy":accuracy_score(y_test,y_pred),

    "Precision":precision_score(y_test,y_pred),

    "Recall":recall_score(y_test,y_pred),

    "F1":f1_score(y_test,y_pred),

    "ROC_AUC":roc_auc_score(y_test,y_prob)

}

with open(

    "hypertension_metrics.json",

    "w"

) as f:

    json.dump(

        metrics,

        f,

        indent=4
    )

from google.colab import files

files.download("hypertension_model.pkl")
files.download("hypertension_feature_columns.pkl")
files.download("hypertension_metrics.json")
files.download("hypertension_best_params.json")
files.download("hypertension_shap_explainer.pkl")
files.download("hypertension_target_encoder.pkl")

