# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOKaTrJu4zqX82U1w_SFHMlPkO6S1B--
"""

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

pd.set_option("display.max_columns", None)

df = pd.read_csv("stroke_data.csv")

print(df.shape)

df.head()

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

print(df.shape)

print(df["stroke"].value_counts())

sns.countplot(x="stroke", data=df)
plt.show()

X = df.drop("stroke", axis=1)

y = df["stroke"]

df.dropna(inplace = True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

feature_columns = X_train.columns.tolist()

joblib.dump(
    feature_columns,
    "stroke_feature_columns.pkl"
)

from xgboost import XGBClassifier

model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_prob = model.predict_proba(X_test)[:,1]

from sklearn.metrics import *

print("Accuracy :",accuracy_score(y_test,y_pred))

print("Precision :",precision_score(y_test,y_pred))

print("Recall :",recall_score(y_test,y_pred))

print("F1 :",f1_score(y_test,y_pred))

print("ROC AUC :",roc_auc_score(y_test,y_prob))

cm = confusion_matrix(y_test,y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.show()

from sklearn.model_selection import RandomizedSearchCV

param_grid = {

    "n_estimators":[100,200,300],

    "max_depth":[3,4,5,6],

    "learning_rate":[0.01,0.05,0.1],

    "subsample":[0.8,0.9,1.0],

    "colsample_bytree":[0.8,0.9,1.0]
}

search = RandomizedSearchCV(

    model,

    param_grid,

    cv=5,

    n_iter=20,

    scoring="roc_auc",

    random_state=42,

    n_jobs=-1

)

search.fit(X_train,y_train)

best_model = search.best_estimator_

y_pred = best_model.predict(X_test)

y_prob = best_model.predict_proba(X_test)[:,1]

joblib.dump(
    best_model,
    "stroke_model.pkl"
)

import json

metrics = {

    "Accuracy":accuracy_score(y_test,y_pred),

    "Precision":precision_score(y_test,y_pred),

    "Recall":recall_score(y_test,y_pred),

    "F1":f1_score(y_test,y_pred),

    "ROC_AUC":roc_auc_score(y_test,y_prob)

}

with open("stroke_metrics.json","w") as f:

    json.dump(metrics,f,indent=4)

import shap

explainer = shap.TreeExplainer(best_model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values,X_test)

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar"
)

joblib.dump(
    explainer,
    "stroke_shap_explainer.pkl"
)

from google.colab import files

files.download("stroke_model.pkl")
files.download("stroke_feature_columns.pkl")
files.download("stroke_metrics.json")
files.download("stroke_shap_explainer.pkl")

